### Data Analysis 3 - Assignment 

Fazile Brahimi

#### Berlin – Earlier Snapshot (Time Validity)

In [1]:
# Import necessary libraries
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv("../data/raw/berlin_2025_Q1_listings.csv")
df.shape

(13945, 79)

In [2]:
# Select relevant columns
cols = [
    "price",
    "accommodates",
    "bedrooms",
    "bathrooms",
    "room_type",
    "latitude",
    "longitude",
    "review_scores_rating",
    "number_of_reviews",
    "amenities"
]

df = df[cols]
df.head()

,price,accommodates,bedrooms,bathrooms,room_type,latitude,longitude,review_scores_rating,number_of_reviews,amenities
0,$105.00,2,1.0,1.0,Entire home/apt,52.53471,13.41810,4.63,149,"[""Bathtub"", ""Dishes and silverware"", ""Bed line..."
1,$135.00,7,4.0,2.5,Entire home/apt,52.53269,13.41805,5.00,7,"[""Bathtub"", ""Dryer"", ""Dishes and silverware"", ..."
2,$75.00,1,0.0,1.0,Entire home/apt,52.54813,13.40366,4.68,26,"[""Heating"", ""Host greets you"", ""Smoke alarm"", ..."
3,$77.00,4,1.0,1.0,Entire home/apt,52.50312,13.43508,4.72,48,"[""Heating"", ""Room-darkening shades"", ""Children..."
4,$40.00,2,0.0,1.0,Entire home/apt,52.49419,13.42166,4.77,299,"[""Dishes and silverware"", ""Luggage dropoff all..."

In [3]:
# Clean and transform the price column

df["price"] = (
    df["price"]
    .replace('[\$,]', '', regex=True)
    .astype(float)
)

df = df[df["price"] > 0]
df["log_price"] = np.log(df["price"])

<>:5: SyntaxWarning: invalid escape sequence '\$'
<>:5: SyntaxWarning: invalid escape sequence '\$'
C:\Users\admin\AppData\Local\Temp\ipykernel_18724\2206484955.py:5: SyntaxWarning: invalid escape sequence '\$'
  .replace('[\$,]', '', regex=True)

##### Airbnb prices are highly right-skewed; therefore, we model the logarithm of price to stabilize variance and improve model performance.

In [4]:
# Handle missing values

df["bedrooms"] = df["bedrooms"].fillna(df["bedrooms"].median())
df["bathrooms"] = df["bathrooms"].fillna(df["bathrooms"].median())
df["review_scores_rating"] = df["review_scores_rating"].fillna(0)
df["number_of_reviews"] = df["number_of_reviews"].fillna(0)
df["room_type"] = df["room_type"].fillna("Unknown")

In [5]:
# Feature engineering on amenities
df["wifi"] = df["amenities"].str.contains("Wifi|Wi-Fi", case=False, na=False).astype(int)
df["kitchen"] = df["amenities"].str.contains("Kitchen", case=False, na=False).astype(int)
df["air_conditioning"] = df["amenities"].str.contains("Air conditioning", case=False, na=False).astype(int)

df = df.drop(columns=["amenities"])

In [6]:
# Save the cleaned dataset
df.to_csv("../data/processed/berlin_2025_Q1_clean.csv", index=False)

### Geneva – Other City (Spatial Validity)

In [7]:
# Load the dataset
df = pd.read_csv("../data/raw/geneva_listings.csv")
df.shape

(2719, 79)

In [8]:
# Select relevant columns
cols = [
    "price",
    "accommodates",
    "bedrooms",
    "bathrooms",
    "room_type",
    "latitude",
    "longitude",
    "review_scores_rating",
    "number_of_reviews",
    "amenities"
]

df = df[cols]
df.head()

,price,accommodates,bedrooms,bathrooms,room_type,latitude,longitude,review_scores_rating,number_of_reviews,amenities
0,$89.00,1,1.0,1.5,Private room,46.20198,6.15672,4.75,82,"[""Elevator"", ""Bathtub"", ""Stove"", ""Iron"", ""Host..."
1,$136.00,2,1.0,1.0,Entire home/apt,46.19964,6.15580,4.91,98,"[""Elevator"", ""Iron"", ""Fire extinguisher"", ""Hos..."
2,$81.00,3,1.0,1.0,Entire home/apt,46.28031,6.16833,4.64,123,"[""Dedicated workspace"", ""Children\u2019s books..."
3,NaN,2,1.0,NaN,Entire home/apt,46.20708,6.15545,4.83,130,"[""Elevator"", ""Dedicated workspace"", ""Iron"", ""F..."
4,$55.00,2,1.0,1.0,Private room,46.18904,6.13908,4.86,61,"[""Elevator"", ""Dedicated workspace"", ""Bathtub"",..."

In [9]:
# Clean and transform the price column

df["price"] = (
    df["price"]
    .replace('[\$,]', '', regex=True)
    .astype(float)
)

df = df[df["price"] > 0]
df["log_price"] = np.log(df["price"])

<>:5: SyntaxWarning: invalid escape sequence '\$'
<>:5: SyntaxWarning: invalid escape sequence '\$'
C:\Users\admin\AppData\Local\Temp\ipykernel_18724\2206484955.py:5: SyntaxWarning: invalid escape sequence '\$'
  .replace('[\$,]', '', regex=True)

In [10]:
# Handle missing values

df["bedrooms"] = df["bedrooms"].fillna(df["bedrooms"].median())
df["bathrooms"] = df["bathrooms"].fillna(df["bathrooms"].median())
df["review_scores_rating"] = df["review_scores_rating"].fillna(0)
df["number_of_reviews"] = df["number_of_reviews"].fillna(0)
df["room_type"] = df["room_type"].fillna("Unknown")

In [11]:
# Feature engineering on amenities
df["wifi"] = df["amenities"].str.contains("Wifi|Wi-Fi", case=False, na=False).astype(int)
df["kitchen"] = df["amenities"].str.contains("Kitchen", case=False, na=False).astype(int)
df["air_conditioning"] = df["amenities"].str.contains("Air conditioning", case=False, na=False).astype(int)

df = df.drop(columns=["amenities"])

In [12]:
# Save the cleaned dataset
df.to_csv("../data/processed/geneva_2025_clean.csv", index=False)